config/routes.rb
Rails.application.routes.draw do
  # get 'events/index'
  # get 'events/new'
  # get 'events/show'
  # get 'events/edit'
  # get 'user_events/index'
  devise_for :users
  get "my_events", to: "user_events#index"
  
  resources :events do 
    resources :attendances
  end
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord 
  belongs_to :attended_event, class_name: 'Event'
  belongs_to :attendee, class_name: 'User'
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: 'User'
    has_many :attendances, foreign_key: :attended_event_id, dependent: :destroy 
    has_many :attendees, through: :attendances
  
    scope :upcoming, -> { where("event_date >= ?", Date.today) }
    scope :past, -> { where("event_date < ?", Date.today) }
    scope :by_date, -> { order(event_date: :asc) }
  
    validates :title, :event_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :events, foreign_key: :creator_id
    has_many :attendances, foreign_key: :attendee_id
    has_many :attended_events, through: :attendances
       
    validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :update_allowed_parameters, if: :devise_controller?
  
    protected
  
    def update_allowed_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password)}
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password)}
    end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
    def create
        @event = Event.find(params[:event_id])
        # attendances -> fill a line in the table attendances with a new attendance
        @attendance = @event.attendances.build({attendee: current_user})    
    
        @attendance.save!               
        # not checking if save works cause no validation needed
        redirect_to event_path(@event)
    end
    
    def destroy 
        @event = Event.find(params[:event_id])
        @attendance = @event.attendances.find(params[:id])
        @attendance.destroy
        # navigates back to event - whole point of associations (belongs_to)
        redirect_to event_path(@attendance.attended_event) 
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create] 

  def index
    @events = Event.by_date
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    # fills in user_id in the new post. current_user = from devise
    @event = current_user.events.build(event_params)  

    if @event.save
      redirect_to events_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path
  end

  private
  
  def event_params
    params.require(:event).permit(:title, :description, :location, :event_date, :event_time)
  end
end

app/controllers/user_events_controller.rb
class UserEventsController < ApplicationController 
    before_action :authenticate_user! 
  
    def index
      @events = current_user.events
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/views/events/_attendance_form.html.erb
<div>
  Want to attend? 
  <% if current_user %>
    <% #if Attendance.where(attendee: current_user, attended_event: @event).exists? %>
    <% # if current_user.attendances.where(attended_event: @event).exists? %>
    <% if (attendance = @event.attendances.find_by(attendee: current_user)) %> <!-- (one = because special case. attendance was not defined ) -->
      Thank you for joining!
      Don't want to attend anymore? 
      <%= button_to "Remove attendance", event_attendance_path(@event, attendance), method: :delete, class: "btn btn-danger", form_class: "d-inline" %>
    <% else %>
      <%= button_to "Click here!", event_attendances_path(@event), class: "btn btn-primary", form_class: "d-inline" %>        
    <% end %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/events/_card.html.erb
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title"> <%= link_to event.title, event %> </h5>     <!-- # 2nd 'event' is the model. rails transforms into event_path (path helper) -->
    <p class="card-text"><%= event.description%> </p>
  </div>
  <div class="card-footer d-flex">
    <div class="p-1 flex-grow-1"></div>
    <div class="p-0">
        <% if current_user == event.creator %>
          <%= link_to edit_event_path(event), class: "card-link" do %><%= image_tag "pencil-outline.svg", title: "Edit event", height: 20 %><% end %>
          <%= button_to event_path(event), method: :delete, class: "card-link btn btn-link ", form_class: "d-inline" do %><%= image_tag "trash-can-outline.svg", title: "Delete event", height: 20 %><% end %>
        <%end%>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<div class="d-flex flex-column align-items-center">
  <div class="col-6">
    <%= form_with model: @event do |form| %>
      <% if @event.errors.any? %>
        <% @event.errors.full_messages.each do |message| %>
          <div><%= message %></div>
        <% end %>
      <% end %>
      <div class="field">
        <%= form.label :title, class: "form-label" %>
        <div><%= form.text_field :title, class: "form-control", autocomplete: 'off', required: true %></div>
      </div>
       <div class="field">
        <%= form.label :location, class: "form-label" %>
        <div><%= form.text_field :location, class: "form-control", autocomplete: 'off' %></div>
      </div>
       <div class="field">
        <%= form.label :event_date, class: "form-label" %>
        <div><%= form.datetime_field :event_date, class: "form-control" %></div>
      </div>
      <div class="field">
        <%= form.label :description, class: "form-label" %>
        <div><%= form.text_area :description, class: "form-control", size: "60x10" %></div>
      </div>
      <div>
        <%= form.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/_list.html.erb
<%if events.empty? %>
  <div class="text-center mt-5"> <%= "There are no events" %> </div>
<% end %>

<div class="d-flex flex-column align-items-center">
  <div class="col-9">
    <% events.each do |event| %>
      <%= render 'events/card', event: event %>
    <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<%= render 'form' %>

app/views/events/index.html.erb
<h1>All events</h1>
<div>
  <h5>Upcoming:</h5>
  <%= render 'list', events: @events.upcoming.by_date %>

  <h5>Past:</h5>
  <%= render 'list', events: @events.past.by_date %>
</div>

app/views/events/new.html.erb
<%= render 'form'%>

app/views/events/show.html.erb
<div class="card mb-3">
  <div class="card-header d-flex">
    <div class="p-1 flex-grow-1"></div>
    <div class="p-0">
        <% if current_user == @event.creator %>
          <%= link_to edit_event_path(@event), class: "card-link" do %><%= image_tag "pencil-outline.svg", title: "Edit event", height: 20 %><% end %>
          <%= button_to event_path(@event), method: :delete, class: "card-link btn btn-link ", form_class: "d-inline" do %><%= image_tag "trash-can-outline.svg", title: "Delete event", height: 20 %><% end %>
        <%end%>
    </div>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @event.title %></h5>
    <p class="card-text"><%= l @event.event_date, format: :long %> </p> 
    <p class="card-text"><%= @event.location%> </p>
    <p class="card-text"><%= @event.description%> </p>

    <%= render 'attendance_form' %>

    <h6 class="mt-5">Currently attending:</h6>

    <ul>
      <% @event.attendees.each do |attendee| %>
        <li><%= attendee.username %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventBrite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg mb-3">
      <div class="container-fluid">
        <%= link_to "Private Events", root_path, class: "navbar-brand me-auto btn btn-outline-primary" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end gap-3" id="navbarSupportedContent">
          <% if current_user %> 
            <%= link_to "New event", new_event_path, class: "btn btn-primary" %>
            <%= link_to "My events", my_events_path, class: "btn btn-primary" %>
            <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
          <% else %>
            <% if controller_name != "sessions" %>
              <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary text-light" %>
            <% end %>
            <% if controller_name != "registrations" %>
              <%= link_to "Sign up",  new_user_registration_path, class: "btn btn-primary text-light" %>
            <% end %>
          <% end%>
        </div>
      </div>
    </nav>

    <div class="container">  
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/user_events/index.html.erb
<h3>Created events:</h3>
<%= render 'events/list', events: @events.upcoming.by_date %>
<h5>Past events:</h5>
<%= render 'events/list', events: @events.past.by_date %>

<h3>Your events:</h3>

<!-- in 'events:' can also put query. current_user has association to attended_events. This is navigation. Could have also added action in user_events_controller and use instance variable-->
<%= render 'events/list', events: current_user.attended_events.upcoming.by_date %> 

<h5>Past events: </h5>
<%= render 'events/list', events: current_user.attended_events.past.by_date  %>